server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taxi_db}
    username: ${SPRING_DATASOURCE_USERNAME:taxi_user}
    password: ${SPRING_DATASOURCE_PASSWORD:taxi_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: true

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8081}